name: Semantic Release

on:
  push:
    branches:
      - main
      - qa

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install python-semantic-release jinja2

      - name: Python Semantic Release
        uses: python-semantic-release/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Changelog
        run: python changelog_templates/semantic.py

      - name: Commit Changelog
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CHANGELOG.md
          git commit -m "chore: Update changelog"
          git push

      - name: Push changes to qa and dev
        if: github.ref == 'refs/heads/main'
        run: |
          git fetch
          git checkout qa
          git merge main
          git push origin qa
          git checkout dev
          git merge qa
          git push origin dev

      - name: Push changes to dev
        if: github.ref == 'refs/heads/qa'
        run: |
          git fetch
          git checkout dev
          git merge qa
          git push origin dev
